version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /var/www/
    pattern: '**'
    mode: 0664
    owner: ec2-user
    group: apache
    type: 
    - file
    - directory
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
  #  - location: scripts/change_permissions.sh
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
  # - location: scripts/create_test_db.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root